CREATE VIEW WITHDRAW_Q AS
SELECT WITHDRAWAL_AMT , "DATE" FROM BANK_TRANSACTION; 

CREATE INDEX WITHDRAW_INDEX
ON BANK_TRANSACTION (WITHDRAWAL_AMT, "DATE");


-- 1) HIGHEST DEBITED AMOUNT IN EACH YEAR
SELECT EXTRACT(YEAR FROM "DATE") AS Year, MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)) AS HighestDebitedAmount
FROM WITHDRAW_Q
WHERE WITHDRAWAL_AMT IS NOT NULL
  AND EXTRACT(YEAR FROM "DATE") IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE");

-- 2) LOWEST DEBITED AMOUNT IN EACH YEAR

-- EXPLAIN PLAN FOR
SELECT EXTRACT(YEAR FROM "DATE") AS Year, MIN(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)) AS HighestDebitedAmount
FROM WITHDRAW_Q
WHERE WITHDRAWAL_AMT IS NOT NULL
  AND EXTRACT(YEAR FROM "DATE") IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE");
-- SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);


