CREATE VIEW WITHDRAW_Q AS
SELECT WITHDRAWAL_AMT , "DATE" FROM BANK_TRANSACTION; 

SELECT EXTRACT(YEAR FROM "DATE") AS Year, MAX(TO_NUMBER(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9]+', ''))) 
AS HighestDebitedAmount
FROM WITHDRAW_Q
GROUP BY EXTRACT(YEAR FROM "DATE");


SELECT EXTRACT(YEAR FROM "DATE") AS Year, MIN(TO_NUMBER(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9]+', ''))) 
AS LowestDebitedAmount
FROM WITHDRAW_Q
GROUP BY EXTRACT(YEAR FROM "DATE");


