CREATE VIEW WITHDRAW_Q AS
SELECT WITHDRAWAL_AMT , "DATE" FROM BANK_TRANSACTION; 

SELECT EXTRACT(YEAR FROM "DATE") AS Year, MAX(WITHDRAWAL_AMT) AS HighestDebitedAmount
FROM WITHDRAW_Q
GROUP BY EXTRACT(YEAR FROM "DATE");

SELECT EXTRACT(YEAR FROM "DATE") AS Year, MIN(WITHDRAWAL_AMT) AS LowestDebitedAmount
FROM WITHDRAW_Q
GROUP BY EXTRACT(YEAR FROM "DATE");
