CREATE TABLE DEMO(
    ID NUMBER,
    NAME VARCHAR(20),
    LOCATION VARCHAR(45)

);

INSERT INTO DEMO VALUES(1,'DEMO','POLAND');
INSERT INTO DEMO VALUES(2,'DEMO1','SYDNEY');
SELECT * FROM DEMO;
DESC DEMO;