SELECT EXTRACT (YEAR FROM "DATE") AS YEAR,
MAX(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)) AS HIGHESTDEBITEDAMOUNT
FROM WITHDRAW_Q
WHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE");




SELECT EXTRACT(YEAR FROM "DATE") AS YEAR,
MIN(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)) AS LOWESTDEBITEDAMOUNT
FROM WITHDRAW_Q
WHERE WITHDRAWAL_AMT IS NOT NULL
GROUP BY EXTRACT(YEAR FROM "DATE");




SELECT YEAR,FIFTHHIGHESTAMOUNT
FROM (
    SELECT
        EXTRACT(YEAR FROM "DATE") AS YEAR,
        CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) AS FIFTHHIGHESTAMOUNT,
        DENSE_RANK() OVER (PARTITION BY EXTRACT(YEAR FROM "DATE") ORDER BY
        CAST (REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) DESC) AS R
        FROM WITHDRAW_Q
        WHERE CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) IS
        NOT NULL
)
WHERE R=5;




SELECT COUNT(CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)) AS WITHDRAWALCOUNT
FROM WITHDRAW_Q
WHERE "DATE" BETWEEN TO_DATE('05-05-2018', 'DD-MM-YYYY') AND TO_DATE ('07-03-2019', 'DD-MM-YYYY');




SELECT DISTINCT EXTRACT(YEAR FROM "DATE") AS YEAR,
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) AS LARGESTWITHDRAWAL
FROM WITHDRAW_Q
WHERE EXTRACT(YEAR FROM "DATE") = 2018 AND
CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER) IS NOT NULL
ORDER BY CAST(REGEXP_REPLACE(WITHDRAWAL_AMT, '[^0-9.]', '') AS NUMBER)
DESC FETCH FIRST 5 ROWS ONLY;